#!/usr/bin/env bash
set -e

defaultBranch=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f 2 | tr -d '[:space:]')

if git branch | grep -qE "(\* ${defaultBranch}|\* \(HEAD detached)"; then
    echo "Can't remaster on current branch" >&2
    exit 1
fi

branch=`git branch | grep \* | cut -d ' ' -f2`
ref=`git rev-parse $branch`
echo "To restore your branch ($branch), run the following:"
echo "  git checkout -b $branch $ref"

git fetch
git rebase -i origin/${defaultBranch}
