#!/usr/bin/env bash
set -e

if git branch | grep -E '^\*' | grep -qE ' (master|\(HEAD detached at origin/master\))$'; then
    echo "Can't post-land on master" >&2
    exit 1
fi

branch=`git branch | grep \* | cut -d ' ' -f2`
ref=`git rev-parse $branch`
echo "To restore your branch ($branch), run the following:"
echo "  git checkout -b $branch $ref"

git fetch
git -c advice.detachedHead=false checkout origin/master
git branch -D $branch
git remote prune origin
