#!/usr/bin/env bash
set -euo pipefail

defaultBranch=$(git-default-branch)

if git branch | grep -qE "(\* ${defaultBranch}|\* \(HEAD detached)"; then
    echo "Can't post-land on current branch" >&2
    exit 1
fi

branch=$(git branch | grep \* | cut -d ' ' -f2)
ref=$(git rev-parse $branch)
echo "To restore your branch ($branch), run the following:"
echo "  git checkout -b $branch $ref"

git fetch
git -c advice.detachedHead=false checkout origin/${defaultBranch}
git branch -D $branch
git remote prune origin
